// js/prompts.js

// 90 Truth Questions
const truthPrompts = {
  A: [
    "What’s your go-to comfort show—and why do you think it soothes you?",
    "What snack is basically your personality in edible form?",
    "If you had to describe your current mood as a color, what would it be?",
    "Have you ever talked to yourself out loud in public without realizing it?",
    "What’s a compliment you secretly love getting?",
    "What’s the silliest lie you ever told as a kid?",
    "If you could magically learn one skill overnight, what would it be?",
    "What’s something you do when no one’s watching that always makes you feel better?",
    "If you were a meme, which one would you be?",
    "What’s a guilty pleasure you think I’d be surprised by?",
    "What’s something small I do that makes you smile inside?",
    "Have you ever cried at a movie you swore wouldn’t get to you?",
    "What’s a silly superstition you kind of believe in anyway?",
    "What’s one totally random thing that turns your day around?",
    "What’s your phone wallpaper and why?",
    "What animal do you relate to most today—and why?",
    "If I gave you a secret nickname, what would you want it to be?",
    "Which emoji combo perfectly sums up our vibe?",
    "If we were cartoon characters, what would our dynamic be?",
    "What’s the last thing you saved on your phone that made you laugh?",
    "What would your personalized ice cream flavor be called?",
    "If I dared you to write a haiku about me, what would it say?",
    "When’s the last time you felt pure joy?",
    "What’s something adorably nerdy you love?",
    "Do you believe in lucky socks, charms, or rituals?",
    "If I made a playlist called 'Us'—what would be track one?",
    "What’s something playful you wish more adults embraced?",
    "What color do you feel like today—and why?",
    "What’s your dream 'do nothing' day with me look like?",
    "If our story was a rom‑com, what would the title be?"
  ],
  B: [
    "What’s something you’ve had to unlearn in order to grow?",
    "What truth have you avoided admitting to yourself until recently?",
    "When have you felt the most emotionally safe in your life?",
    "What’s a pattern you’ve noticed in your relationships?",
    "When do you feel most vulnerable with me?",
    "What’s something about yourself that you’re still learning to accept?",
    "What does being seen mean to you—really?",
    "What’s a moment you wish you could go back and reassure yourself in?",
    "When you think about love, what scares you the most?",
    "Have you ever felt like you loved someone more than they loved you?",
    "What part of your past still echoes in your present?",
    "What do you crave more—comfort or growth?",
    "What do you believe you bring to a relationship that’s rare or special?",
    "What does emotional intimacy mean to you in a physical space?",
    "Is there a version of yourself that you miss?",
    "What boundary have you struggled to hold—and why?",
    "When was the last time you truly forgave someone?",
    "What would you say if you could send a message to a past version of you?",
    "What’s something you’ve never told a partner because it felt too raw?",
    "How do you know when you’re safe to let your guard down?",
    "If you could rewrite one narrative you’ve carried for years, what would it be?",
    "What’s a wound that still needs gentleness, not fixing?",
    "What emotion is hardest for you to express in front of someone else?",
    "What does loyalty mean to you on your worst days?",
    "When was the last time you felt truly proud of yourself?",
    "What truth about your body or mind has taken the longest to accept?",
    "What do you do when you feel invisible?",
    "If I asked what your heart wants most right now, what would it whisper?",
    "What’s one belief you hold that’s been shaped by pain?",
    "How do you want to be loved when you’re not okay?"
  ],
  C: [
    "What part of your body do you wish someone would kiss more often?",
    "What’s a sexy compliment that instantly gets to you?",
    "What type of foreplay is underrated in your opinion?",
    "When do you feel the most irresistible?",
    "What kind of touch makes you melt instantly?",
    "Have you ever had a fantasy so strong it stayed with you for days?",
    "What’s something you’ve always wanted to whisper in the dark?",
    "If we had one night where we both had zero inhibitions, what would you want?",
    "What’s a scent or sound that turns you on unexpectedly?",
    "What’s the most unexpected place you’ve ever gotten turned on?",
    "What kind of teasing drives you wild—physical or mental?",
    "Have you ever imagined what I look like when I’m turned on?",
    "What’s one thing you wish I’d do to you with no hesitation?",
    "If I were to kiss just one spot on you for 5 minutes, where would you choose?",
    "What’s your favorite position—to be admired in?",
    "What outfit or type of clothing makes you feel secretly sexy?",
    "What’s something you’d love for me to say to you in bed?",
    "What’s the most intense turn‑on you’ve felt with just a look?",
    "Have you ever fantasized about seducing me in public?",
    "Describe the last time you got turned on without being touched.",
    "What’s something you want me to take my time discovering?",
    "Do you like giving control, taking control, or the back‑and‑forth?",
    "What’s the sexiest non‑sexual act someone can do for you?",
    "Have you ever had a dream about us? What happened?",
    "What song makes you feel sexy and powerful?",
    "Do you enjoy being worshiped—or doing the worshiping?",
    "What does your most seductive version of self look like?",
    "Have you ever been kissed in a way that made time stop?",
    "Describe what it feels like when you’re about to lose control.",
    "If I could read your thoughts right now, what would surprise me most?"
  ]
};

// 90 Bare Prompts
const barePrompts = {
  A: [
    "Snap a pic of something small that made you smile today.",
    "Send a voice note pretending you're my GPS.",
    "Draw a doodle of how you think I see you (stick figures encouraged).",
    "Take a photo of the coziest spot in your house.",
    "Send me a pic of the most random item in your purse or bag right now.",
    "Record yourself humming your go-to shower song.",
    "Snap a pic of your feet as if you're doing a foot model audition.",
    "Take a selfie pretending you're mad at me for something silly.",
    "Send your best attempt at a cartoon voice.",
    "Record your fake acceptance speech for an imaginary award.",
    "Use emojis only to describe how you felt when we first started talking.",
    "Send a picture of something Deborah-colored (whatever that means to you).",
    "Take a pic with a funny filter and give it a backstory.",
    "Send a pic of the last snack you regretted eating.",
    "Snap a photo of your happy place (real or symbolic).",
    "Send your best impersonation of a character from your favorite show.",
    "Draw your current mood as a weather report.",
    "Send your favorite childhood toy if you still have it (or describe it).",
    "Send a screenshot of your most used emoji combo.",
    "Write a text as if you were me flirting with you.",
    "Take a mirror selfie but strike a superhero pose.",
    "Send your best “Who, me?” innocent look.",
    "Record a 5‑second voicemail as if you're calling to say 'I miss you.'",
    "Send a pic of your drink of choice like it’s a dating profile pic.",
    "Draw a tattoo you'd give me if I had to get one today.",
    "Send a picture of the weirdest object near you with zero explanation.",
    "Write a haiku about how I make you feel.",
    "Send a pic of the sky right now from where you are.",
    "Record yourself saying your favorite word with dramatic flair.",
    "Take a pic of your hands doing something cute or random."
  ],
  B: [
    "Voice note: what's one moment you think shaped who you are?",
    "Text me something you'd only admit if you felt totally safe.",
    "Describe in one sentence a time you felt misunderstood.",
    "Send a pic of something that represents your inner world.",
    "Record a thought you’ve had about us that you haven’t shared yet.",
    "Tell me one way you've grown in the past year.",
    "Text me your definition of emotional intimacy.",
    "Send a photo of something from your past you still keep for comfort.",
    "Voice message: what scares you about love?",
    "Send three words that capture your hopes for connection.",
    "Describe a moment where you felt truly seen by someone.",
    "Voice note: share a compliment you wish someone had given you.",
    "Text me something you’ve healed from that you’re proud of.",
    "What’s something you’re still learning to believe about yourself?",
    "Send a photo of a book, quote, or object that reflects your current mindset.",
    "Voice message: what does trust mean to you in one sentence?",
    "Name something you’re afraid to want.",
    "Text me one secret dream you haven’t pursued yet.",
    "Tell me what 'home' means to you.",
    "Share something you wish people would stop assuming about you.",
    "Send me a lyric that hits your soul.",
    "What’s one lesson you keep relearning the hard way?",
    "Voice message: describe the most honest version of you.",
    "Send a selfie without looking at it first.",
    "Text me the biggest compliment you’ve ever received and believed.",
    "What’s one boundary you’ve had to build?",
    "Share something about your past that still surprises you.",
    "Text me your biggest 'aha' moment in therapy (or life).",
    "Send a pic of a place that helped you change.",
    "Name one fear you’re working on facing right now."
  ],
  C: [
    "Send a close-up of your lips with a flirtatious caption.",
    "Voice note: say the word 'yes' like you mean it... three different ways.",
    "Take a sultry photo of your neckline or collarbone.",
    "Whisper something naughty you'd *almost* say out loud.",
    "Send a pic of what you’d wear if I dared you to distract me.",
    "Text me the title of the playlist you’d make for a night alone with me.",
    "Send a blurred pic that teases more than it shows.",
    "Voice message: describe where you'd want my hands to be right now.",
    "Show me your pillow... and tell me what happened on it last night.",
    "Text me one dirty thought you’ve had about me today.",
    "Send a pic of your favorite under-the-radar sensual spot.",
    "Whisper in a voice note what you’d do to me if there were no rules.",
    "Send a pic that starts innocent but feels suggestive.",
    "Text me a safe word you’d choose and why.",
    "Take a photo of the part of your outfit that’s making you feel confident.",
    "Voice note: say my name like you’re summoning me to bed.",
    "Text me the last thing you touched that gave you chills.",
    "Send a pic of your legs or thighs in whatever pose feels good.",
    "Send me a one-sentence fantasy you’ve never shared.",
    "Text me a body part of mine you’re most curious about.",
    "Voice note: tease me without saying anything explicit.",
    "Snap a mirror pic with a sly smile like you’ve got a secret.",
    "Send a pic of something that makes you feel soft and seductive.",
    "Text me a line from a dream where I showed up.",
    "Send a pic from your bed POV—just sheets and vibes.",
    "Write a flirty one-liner like it’s our first text ever.",
    "Send a selfie where you’re almost biting your lip.",
    "Record yourself breathing... just breathing, but slow and intimate.",
    "Send a pic of your reflection in something other than a mirror.",
    "Text me a dare you secretly hope I accept."
  ]
};
